### PR TITLE
fix: could not find a declaration file for module 'ansis'

### PR DESCRIPTION
**Pull request by will-stone**
## Types of changes

This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **docs change**
- [ ] **breaking change** 

## Motivation / Use-Case

Fixes this TypeScript error:

CleanShot 2023-11-14 at 12 35 41@2x

## Breaking Changes

None

## Additional Info

---

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have updated the **CHANGELOG.md**.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by will-stone** [comment]
hang on! @webdiscus what's this file? https://github.com/webdiscus/ansis/blob/master/pkg/package.json why is there two package.json files?

**Comment by webdiscus** [comment]
> hang on! @webdiscus what's this file? https://github.com/webdiscus/ansis/blob/master/pkg/package.json why is there two package.json files?

Hello @will-stone,

can you please add the `types.d.ts` to the `pkg/package.json` too.

We have 2 package.json files:

- `./package.json` - the file for local development and contribution.
   The source code is written as ESM, therefore for local development is required the `"type": "module"` here.
   The main file is defined as source file: `"main": "./src/index.js"` for tests.
- `./pkg/package.json` - the clean & small file for NPM package, containing different fields.
   The NPM package contains "compiled" universal (ESM/CJS) code, therefore is required different file with other `"main": "./index.js"` and the type of  the package is not `module`.

**Comment by webdiscus** [comment]
can you please change the `"version": "2.0.2",` field in both `package.json` and `pkg/package.json` files

**Comment by will-stone** [comment]
Done and done 👍

**Comment by webdiscus** [comment]
@will-stone  the `v2.0.2` is deployed.

Thank you!

**Comment by will-stone** [comment]
Oh awesome! thanks for the quick turnaround 🥳

**Pull request merged**
